name: Continuous integration
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 1,15 * *"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    steps:
      - name: Install Rust environment
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.OS }}-build-
      - name: Build library
        run: cargo build
      - name: Run test suite
        run: cargo test
        env:
          PROPTEST_CASES: 2500
